Repository kubevirt/kubevirt-ansible, pull requests merged in 2018-12, with the labels that each got.

#491 Removed use of duplicate namespace in RunCommand function
  tests/framework/cli_exec.go
Labels: release-note-none, size/XS

#507 fix: invalid urls and typos
  CONTRIBUTING.md
  playbooks/README.md
  roles/kubevirt/README.md
Labels: release-note-none, size/S

#486 [Virt] Add clear namespace from resources before each test
  tests/high_performance_vm_test.go
  tests/virtio_rng_test.go
  tests/vm_with_sidecar_hook_test.go
Labels: release-note-none, size/S

#514 adding missing apb params
  roles/network-multus/defaults/main.yml
Labels: release-note-none, size/XS

#496 Support SR-IOV deployment
  playbooks/kubevirt.yml
  playbooks/sriovdp-config.json
  roles/kubevirt/templates/kubevirt-config.yaml
  roles/network-multus/defaults/main.yml
  roles/network-multus/tasks/provision.yml
  roles/network-multus/templates/sriov-cni.yml
  roles/network-multus/templates/sriov-crd.yml
  roles/network-multus/templates/sriovdp.yml
  vars/all.yml
Labels: release-note, size/L

#488 Some clarifications and fixes for playbooks/ README
  playbooks/README.md
Labels: release-note-none, size/S

#511 remove multus conf on deprovision
  playbooks/network.yml
Labels: release-note-none, size/S

#480 Update to OKD 3.11
  automation/check-patch.openshift_3-10.sh
  automation/check-patch.openshift_3-11.mounts
  automation/check-patch.openshift_3-11.packages
  automation/check-patch.openshift_3-11.repos
  automation/check-patch.openshift_3-11.sh
  automation/check-patch.openshift_3-11.yumrepos
  automation/check-patch.sh
  playbooks/cluster/openshift/vars/3.10.yml
  playbooks/cluster/openshift/vars/3.11.yml
  playbooks/provider/lago/LagoInitFile.yml.j2
  roles/kubevirt_web_ui/tasks/deprovision.yml
  stdci.yaml
  tests/vm_with_sidecar_hook_test.go
Labels: release-note-none, size/M

#493 Add tests for, serviceAccount as volumes
  tests/framework/util.go
  tests/serviceaccount_test.go
Labels: release-note-none, size/L

#517 Remove spc_t for sriovdp
  playbooks/kubevirt.yml
  roles/network-multus/templates/sriovdp.yml
Labels: release-note-none, size/XS

#521 Add selector to ovs-vsctl template
  roles/network-multus/templates/ovs-vsctl.yml
Labels: do-not-merge/release-note-label-needed, size/XS

#524 readme: fix kubernetes/kubevirt typo
  README.md
Labels: release-note-none, size/XS

#526 Allowed to run the playbook on a remote server and not only on the master
  .gitignore
  automation/check-patch.sh
  playbooks/cdi.yml
  playbooks/initial_configuration.yml
  playbooks/kubevirt-web-ui.yml
  playbooks/kubevirt-web-ui/private/config.yml
  playbooks/kubevirt-web-ui/private/redeploy-certificates.yml
  playbooks/kubevirt.yml
  playbooks/network.yml
  playbooks/storage.yml
  roles/cdi/tasks/provision.yml
  roles/kubevirt/README.md
  roles/kubevirt/defaults/main.yml
  roles/kubevirt/tasks/deprovision.yml
  roles/kubevirt/tasks/provision.yml
  roles/kubevirt_web_ui/defaults/main.yml
  roles/kubevirt_web_ui/tasks/required_params.yml
  roles/network-multus/README.md
  roles/network-multus/defaults/main.yml
  roles/network-multus/tasks/deprovision.yml
  roles/network-multus/tasks/provision.yml
  roles/network-multus/templates/cni-plugins.yml
  roles/network-multus/templates/multus.yml
  roles/network-multus/templates/ovs-cni.yml
  roles/network-multus/templates/ovs-vsctl.yml
  roles/network-multus/templates/sriov-cni.yml
  roles/network-multus/templates/sriov-crd.yml
  roles/network-multus/templates/sriovdp-config.json
  roles/network-multus/templates/sriovdp.yml
  roles/skydive/README.md
  roles/skydive/defaults/main.yml
  roles/skydive/tasks/provision.yml
  roles/storage-demo/README.md
  roles/storage-demo/defaults/main.yml
  roles/storage-demo/tasks/deprovision.yml
  roles/storage-demo/tasks/provision.yml
  roles/storage-demo/templates/storage-demo.yml
  roles/storage-glusterfs/tasks/deprovision.yml
  roles/storage-glusterfs/tasks/provision.yml
  vars/all.yml
Labels: release-note, size/L
