Repository kubevirt/kubevirt-ansible, pull requests merged in 2018-11, with the labels that each got.

#418 Include "kubevirt-web-ui" playbook in the "kubevirt"
  inventory
  playbooks/kubevirt-web-ui/README.md
  playbooks/kubevirt-web-ui/private/config.yml
  playbooks/kubevirt.yml
  roles/kubevirt_web_ui/defaults/main.yml
  roles/kubevirt_web_ui/tasks/deprovision.yml
  roles/kubevirt_web_ui/tasks/main.yml
  roles/kubevirt_web_ui/tasks/provision.yml
  roles/kubevirt_web_ui/tasks/remove.yml
Labels: release-note, size/M

#435 Deprovision is missing args
  automation/check-patch.sh
Labels: release-note-none, size/XS

#395 High performance VM test
  tests/high_performance_vm_test.go
  tests/manifests/virt-testing-vm.yml
  tests/util.go
Labels: do-not-merge/release-note-label-needed, size/L

#433 Login as the super user first
  playbooks/kubevirt.yml
  roles/kubevirt/tasks/deprovision.yml
  roles/kubevirt/tasks/provision.yml
  roles/network-multus/tasks/provision.yml
Labels: release-note-none, size/S

#421 update typo
  playbooks/kubevirt-web-ui/README.md
Labels: release-note-none, size/XS

#419 [VIRT] VirtIO RNG testing
  tests/virtio_rng_test.go
Labels: do-not-merge/release-note-label-needed, size/M

#443 Increase timeout when validating oc cmd results
  tests/util.go
Labels: release-note-none, size/S

#427 [Virt] VM with sidecar hook test
  tests/manifests/vm_with_sidecar_hook.yml
  tests/util.go
  tests/vm_with_sidecar_hook_test.go
Labels: do-not-merge/release-note-label-needed, size/L

#445 Make sure we use an unused weavenet network
  roles/kubernetes-master/files/weavenet.sh
  roles/kubernetes-master/tasks/main.yml
  roles/kubernetes-master/vars/main.yml
Labels: do-not-merge/release-note-label-needed, size/S

#334 Allow masters to run pods with a simpler command
  roles/kubernetes-master/templates/deploy_kubernetes.j2
Labels: lifecycle/stale

#333 Ignore crd validations to run on latest k8s
  roles/kubevirt/tasks/provision.yml
Labels: lifecycle/stale

#438 Skydive fork
  automation/check-patch.sh
  playbooks/kubevirt.yml
  playbooks/network.yml
  roles/skydive/README.md
  roles/skydive/defaults/main.yml
  roles/skydive/tasks/deprovision.yml
  roles/skydive/tasks/main.yml
  roles/skydive/tasks/provision.yml
  roles/skydive/templates/kubernetes-skydive.yaml
  roles/skydive/templates/openshift-skydive.yaml
Labels: release-note, size/L

#444 Collect obj description on test failure
  tests/tests_suite_test.go
  tests/util.go
Labels: release-note-none, size/L

#448 Add kubevirt feature gate config
  roles/kubevirt/tasks/provision.yml
  roles/kubevirt/templates/.gitignore
  roles/kubevirt/templates/kubevirt-config.yaml
Labels: release-note-none, size/S

#450 Auto-compose of kubevirt_web_ui_image_name for kubevirt-apb flow
  playbooks/kubevirt-web-ui/README.md
  roles/kubevirt_web_ui/tasks/required_params.yml
Labels: release-note-none, size/M

#451 Backport 24fc8ed9 927e5c818
  playbooks/kubevirt-web-ui/README.md
  roles/kubevirt/tasks/provision.yml
  roles/kubevirt/templates/.gitignore
  roles/kubevirt/templates/kubevirt-config.yaml
  roles/kubevirt_web_ui/tasks/required_params.yml
Labels: release-note-none, size/M

#446 Replace cluster extra var with platform
  playbooks/kubevirt-web-ui/README.md
  playbooks/kubevirt-web-ui/private/config.yml
  playbooks/kubevirt.yml
  roles/cdi/README.md
  roles/cdi/defaults/main.yml
  roles/cdi/tasks/provision.yml
  roles/kubevirt/tasks/deprovision.yml
  roles/kubevirt/tasks/provision.yml
  roles/network-multus/tasks/deprovision.yml
  roles/network-multus/tasks/provision.yml
  roles/skydive/tasks/deprovision.yml
  roles/skydive/tasks/provision.yml
  roles/storage-demo/tasks/provision.yml
  roles/storage-glusterfs/tasks/deprovision.yml
  roles/storage-glusterfs/tasks/provision.yml
Labels: release-note-none, size/L

#452 APB fixes backport
  playbooks/kubevirt-web-ui/README.md
  playbooks/kubevirt-web-ui/private/config.yml
  playbooks/kubevirt.yml
  roles/cdi/README.md
  roles/cdi/defaults/main.yml
  roles/cdi/tasks/provision.yml
  roles/kubevirt/tasks/deprovision.yml
  roles/kubevirt/tasks/provision.yml
  roles/network-multus/tasks/deprovision.yml
  roles/network-multus/tasks/provision.yml
  roles/storage-demo/tasks/provision.yml
  roles/storage-glusterfs/tasks/deprovision.yml
  roles/storage-glusterfs/tasks/provision.yml
Labels: release-note-none, size/M

#464 Fix kubevirt-web-ui for kubevirt-apb
  playbooks/kubevirt-web-ui/private/config.yml
  roles/kubevirt_web_ui/defaults/main.yml
  roles/kubevirt_web_ui/tasks/deprovision.yml
  roles/kubevirt_web_ui/tasks/provision.yml
  roles/kubevirt_web_ui/tasks/start.yml
Labels: release-note-none, size/M

#465 [release-0.9] Fix kubevirt-web-ui for kubevirt-apb
  playbooks/kubevirt-web-ui/private/config.yml
  roles/kubevirt_web_ui/defaults/main.yml
  roles/kubevirt_web_ui/tasks/deprovision.yml
  roles/kubevirt_web_ui/tasks/provision.yml
  roles/kubevirt_web_ui/tasks/start.yml
Labels: release-note-none, size/M

#469 Set flaky CDI test in pending mode
  tests/e2e_test.go
Labels: release-note-none, size/XS

#453 [VIRT] Fix sidecar expector
  tests/util.go
Labels: do-not-merge/release-note-label-needed, size/XS

#466 RBAC tests update with error handling
  tests/rbac_test.go
  tests/util.go
Labels: release-note-none, size/M

#431 Fix CDI 1.3 importer pod deletion logic change
  tests/e2e_test.go
  tests/manifests/golden-pvc.yml
Labels: release-note, size/XS

#473 Framework Refactor: episode 1 split files and move into framework package
  tests/e2e_test.go
  tests/framework/cli_exec.go
  tests/framework/namespace.go
  tests/framework/obj_dump.go
  tests/framework/types.go
  tests/framework/user.go
  tests/framework/util.go
  tests/framework/vnc_console.go
  tests/high_performance_vm_test.go
  tests/node_eviction_test.go
  tests/rbac_test.go
  tests/tests_suite_test.go
  tests/types.go
  tests/util.go
  tests/v2v_test.go
  tests/virtio_rng_test.go
  tests/vm_with_sidecar_hook_test.go
Labels: release-note-none, size/XXL

#478 Add tests for, secrets and configmap as volumes
  tests/framework/util.go
  tests/secrets_and_cfgmap_test.go
Labels: release-note, size/L

#391 Define VM type and its behavior
  tests/framework/types.go
  tests/node_eviction_test.go
  tests/rbac_test.go
Labels: size/L
