Repository kubevirt/kubevirt-ansible, pull requests merged in 2018-10, with the labels that each got.

#400 Add Issue and Pull Request templates for github
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-note-none, size/M

#403 e2e-tests: move e2e tests to proper package
  tests/e2e_test.go
Labels: release-note-none, size/S

#352 [RFR] Added v2v tests
  tests/manifests/import-vm-v2v-apb.yml
  tests/v2v_test.go
Labels: size/L

#407 Adding image_pull_policy
  roles/kubevirt/defaults/main.yml
  vars/all.yml
Labels: release-note-none, size/XS

#410 Infra fixes
  automation/check-patch.sh
  hack/build-tests.sh
  hack/dockerized.sh
  playbooks/cluster/openshift/vars/gluster.yml
Labels: release-note-none, size/S

#406 cdi: Apply privileged scc to the correct namespace
  roles/cdi/tasks/provision.yml
Labels: release-note, size/XS

#402 Change default Multus CNI from flannel to weave-net
  roles/network-multus/defaults/main.yml
Labels: release-note, size/XS

#414 Increase Nodes RAM
  playbooks/provider/lago/LagoInitFile.yml.j2
Labels: release-note-none, size/XS

#393 Introduce playbook for Kubevirt UI installation
  playbooks/kubevirt-web-ui/README.md
  playbooks/kubevirt-web-ui/config.yml
  playbooks/kubevirt-web-ui/inventory_example.ini
  playbooks/kubevirt-web-ui/private/config.yml
  playbooks/kubevirt-web-ui/private/redeploy-certificates.yml
  playbooks/kubevirt-web-ui/private/roles
  roles/kubevirt_web_ui/README.md
  roles/kubevirt_web_ui/defaults/main.yml
  roles/kubevirt_web_ui/files/console-config.yaml
  roles/kubevirt_web_ui/files/console-template.yaml
  roles/kubevirt_web_ui/meta/main.yaml
  roles/kubevirt_web_ui/tasks/console-config.yml
  roles/kubevirt_web_ui/tasks/install.yml
  roles/kubevirt_web_ui/tasks/main.yml
  roles/kubevirt_web_ui/tasks/remove.yml
  roles/kubevirt_web_ui/tasks/start.yml
  roles/kubevirt_web_ui/vars/main.yml
Labels: size/XL

#389 Suport jinjia template for CDI
  playbooks/kubevirt.yml
  roles/cdi/README.md
  roles/cdi/defaults/main.yml
  roles/cdi/tasks/deprovision.yml
  roles/cdi/tasks/provision.yml
Labels: size/M

#425 Use a static version for glusterfs server image
  playbooks/cluster/openshift/vars/3.10.yml
  playbooks/cluster/openshift/vars/gluster.yml
Labels: release-note-none, size/XS

#388 [RFR] RBAC testing.
  tests/rbac_test.go
  tests/util.go
Labels: size/L

#426 change cdi_namespace from golden-images to kube-system
  roles/cdi/README.md
  roles/cdi/defaults/main.yml
  roles/storage-demo/defaults/main.yml
Labels: release-note-none, size/XS

#417 Reduce required parameters for kubevirt-web-ui playbook
  playbooks/kubevirt-web-ui/README.md
  playbooks/kubevirt-web-ui/inventory_example.ini
  roles/kubevirt_web_ui/defaults/main.yml
  roles/kubevirt_web_ui/tasks/console-config.yml
  roles/kubevirt_web_ui/tasks/install.yml
  roles/kubevirt_web_ui/tasks/main.yml
  roles/kubevirt_web_ui/tasks/required_params.yml
Labels: release-note, size/M
