Repository kubevirt/kubevirt-ansible, pull requests merged in 2018-03, with the labels that each got.

#111 readme: fix link to docker-storage-defaults and example
  README.md
Labels: docs, enhancement

#105 Fix role kubernetes-node not found
  playbooks/cluster/kubernetes/config.yml
Labels: bug, cluster:k8s

#118 Only enable epel for CentOS and RedHat
  playbooks/cluster/openshift/config.yml
Labels: cluster:osp, enhancement

#127 automation: adding disk for gluster storage
  playbooks/provider/lago/LagoInitFile.yml
  playbooks/provider/lago/config.yml
Labels: automation

#133 REDAME: clear our section about docker storage
  playbooks/README.md
Labels: docs

#154 Add readme template for roles
  CONTRIBUTING.md
  templates/roles_README.md
Labels: docs

#157 Fix task of remove firewalld package
  roles/kubernetes-prerequisites/tasks/main.yml
Labels: enhancement

#156 Update READMEs
  README.md
  playbooks/README.md
  playbooks/cluster/openshift/README.md
  playbooks/provider/lago/README.md
  roles/cdi/README.md
  roles/cluster-login/README.md
  roles/kubevirt/README.md
  roles/storage-cns/README.md
  roles/storage-demo-nodeconfig/README.md
  roles/storage-demo/README.md
  vars/README.md
Labels: docs

#167 role kubevirt: fixed warning about using jinja in when stmt
  roles/kubevirt/tasks/provision.yml
Labels: enhancement

#172 Fix for Issue#158: Making kubevirt-ansible more idempotent
  roles/cdi/tasks/provision.yml
Labels: enhancement
