Repository kubevirt/kubevirt-ansible, pull requests merged in 2019-01, with the labels that each got.

#529 Allow runc on the skydive deployment.
  automation/check-patch.sh
  roles/skydive/defaults/main.yml
  roles/skydive/templates/kubernetes-skydive.yaml
  roles/skydive/templates/openshift-skydive.yaml
Labels: release-note, size/M

#533 Add feature gates to kubevirt-config
  roles/kubevirt/templates/kubevirt-config.yaml
Labels: enhancement, size/XS

#535 fix kubevirt-web-ui tag when docker_tag is configured
  automation/check-patch.sh
  roles/kubevirt/tasks/deprovision.yml
  roles/kubevirt_web_ui/tasks/required_params.yml
Labels: release-note-none, size/XS

#500 add templates test verification testcase
  tests/templates_verification_test.go
Labels: do-not-merge/release-note-label-needed, size/M

#541 Change the offline template to rpm template and increase multus timeout
  roles/kubevirt/defaults/main.yml
  roles/kubevirt/tasks/provision.yml
  roles/network-multus/tasks/provision.yml
Labels: release-note, size/L

#543 Fix cdi to provision and deprovision
  roles/cdi/tasks/deprovision.yml
  roles/cdi/tasks/provision.yml
  roles/cdi/templates/cdi-controller-deployment.yml
  roles/kubevirt/tasks/provision.yml
Labels: release-note, size/L

#539 distribute sr-iov configuration using initContainer
  playbooks/network.yml
  roles/network-multus/templates/cni-plugins.yml
  roles/network-multus/templates/sriovdp-config.json
Labels: do-not-merge/release-note-label-needed, size/M

#544 Web UI: Adapt playbook to use Operator
  playbooks/kubevirt-web-ui.yml
  playbooks/kubevirt-web-ui/README.md
  playbooks/kubevirt-web-ui/config.yml
  playbooks/kubevirt-web-ui/inventory_example.ini
  playbooks/kubevirt-web-ui/private/config.yml
  playbooks/kubevirt-web-ui/private/redeploy-certificates.yml
  playbooks/kubevirt-web-ui/private/roles
  playbooks/kubevirt.yml
  playbooks/kubevirt_web_ui.yml
  roles/kubevirt_web_ui/README.md
  roles/kubevirt_web_ui/defaults/main.yml
  roles/kubevirt_web_ui/files/console-config.yaml
  roles/kubevirt_web_ui/files/console-template.yaml
  roles/kubevirt_web_ui/files/crds/kubevirt_v1alpha1_kwebui_cr.yaml
  roles/kubevirt_web_ui/files/crds/kubevirt_v1alpha1_kwebui_crd.yaml
  roles/kubevirt_web_ui/files/operator.yaml
  roles/kubevirt_web_ui/files/role.yaml
  roles/kubevirt_web_ui/files/role_binding.yaml
  roles/kubevirt_web_ui/files/role_binding_extra_for_console.yaml
  roles/kubevirt_web_ui/files/role_extra_for_console.yaml
  roles/kubevirt_web_ui/files/service_account.yaml
  roles/kubevirt_web_ui/meta/main.yaml
  roles/kubevirt_web_ui/tasks/console-config.yml
  roles/kubevirt_web_ui/tasks/deprovision.operator.yml
  roles/kubevirt_web_ui/tasks/deprovision.web-ui.yml
  roles/kubevirt_web_ui/tasks/deprovision.yml
  roles/kubevirt_web_ui/tasks/main.yml
  roles/kubevirt_web_ui/tasks/provision.operator.yml
  roles/kubevirt_web_ui/tasks/provision.web-ui.yml
  roles/kubevirt_web_ui/tasks/provision.yml
  roles/kubevirt_web_ui/tasks/required_params.yml
  roles/kubevirt_web_ui/tasks/start.yml
  vars/all.yml
Labels: release-note, size/XXL

#557 kubevirt_web_ui_version variable is prefixed with `v`
  roles/kubevirt_web_ui/README.md
  vars/all.yml
Labels: release-note-none, size/S

#505 remove namespace duplication
  tests/framework/cli_exec.go
  tests/framework/util.go
Labels: release-note-none, size/S

#555 Backport: Web UI: Adapt playbook to use Operator
  playbooks/kubevirt-web-ui.yml
  playbooks/kubevirt-web-ui/README.md
  playbooks/kubevirt-web-ui/config.yml
  playbooks/kubevirt-web-ui/inventory_example.ini
  playbooks/kubevirt-web-ui/private/config.yml
  playbooks/kubevirt-web-ui/private/redeploy-certificates.yml
  playbooks/kubevirt-web-ui/private/roles
  playbooks/kubevirt.yml
  playbooks/kubevirt_web_ui.yml
  roles/kubevirt_web_ui/README.md
  roles/kubevirt_web_ui/defaults/main.yml
  roles/kubevirt_web_ui/files/console-config.yaml
  roles/kubevirt_web_ui/files/console-template.yaml
  roles/kubevirt_web_ui/files/crds/kubevirt_v1alpha1_kwebui_cr.yaml
  roles/kubevirt_web_ui/files/crds/kubevirt_v1alpha1_kwebui_crd.yaml
  roles/kubevirt_web_ui/files/operator.yaml
  roles/kubevirt_web_ui/files/role.yaml
  roles/kubevirt_web_ui/files/role_binding.yaml
  roles/kubevirt_web_ui/files/role_binding_extra_for_console.yaml
  roles/kubevirt_web_ui/files/role_extra_for_console.yaml
  roles/kubevirt_web_ui/files/service_account.yaml
  roles/kubevirt_web_ui/meta/main.yaml
  roles/kubevirt_web_ui/tasks/console-config.yml
  roles/kubevirt_web_ui/tasks/deprovision.operator.yml
  roles/kubevirt_web_ui/tasks/deprovision.web-ui.yml
  roles/kubevirt_web_ui/tasks/deprovision.yml
  roles/kubevirt_web_ui/tasks/main.yml
  roles/kubevirt_web_ui/tasks/provision.operator.yml
  roles/kubevirt_web_ui/tasks/provision.web-ui.yml
  roles/kubevirt_web_ui/tasks/provision.yml
  roles/kubevirt_web_ui/tasks/required_params.yml
  roles/kubevirt_web_ui/tasks/start.yml
  vars/all.yml
Labels: release-note, size/XXL

#558 Web UI: Block playbook execution till deployment is finished
  roles/kubevirt_web_ui/files/crds/kubevirt_v1alpha1_kwebui_cr.yaml
  roles/kubevirt_web_ui/tasks/main.yml
  roles/kubevirt_web_ui/tasks/provision.web-ui.yml
  vars/all.yml
Labels: release-note-none, size/S

#536 Replace kubevirt deploy tasks with the operator
  README.md
  roles/kubevirt/defaults/main.yml
  roles/kubevirt/tasks/deprovision.yml
  roles/kubevirt/tasks/provision.yml
  roles/kubevirt/templates/.gitignore
  roles/kubevirt/templates/kubevirt-cr.yaml.j2
  roles/kubevirt/templates/kubevirt-operator.yaml.j2
  vars/all.yml
Labels: release-note, size/L

#564 Replace kubevirt deploy tasks with the operator (#536)
  README.md
  roles/kubevirt/defaults/main.yml
  roles/kubevirt/tasks/deprovision.yml
  roles/kubevirt/tasks/provision.yml
  roles/kubevirt/templates/.gitignore
  roles/kubevirt/templates/kubevirt-cr.yaml.j2
  roles/kubevirt/templates/kubevirt-operator.yaml.j2
  vars/all.yml
Labels: release-note, size/L

#566 Backport: Web UI: Block playbook execution
  roles/kubevirt_web_ui/README.md
  roles/kubevirt_web_ui/files/crds/kubevirt_v1alpha1_kwebui_cr.yaml
  roles/kubevirt_web_ui/tasks/main.yml
  roles/kubevirt_web_ui/tasks/provision.web-ui.yml
  vars/all.yml
Labels: release-note-none, size/M

#567 Limit the feature gates to SRIOV and DataVolumes in 0.12.0
  roles/kubevirt/templates/kubevirt-config.yaml
Labels: release-note-none, size/XS

#559 Add templates deployment to kubevirt ansible
  playbooks/kubevirt-ssp.yml
  playbooks/kubevirt.yml
  roles/kubevirt-ssp/README.md
  roles/kubevirt-ssp/defaults/main.yml
  roles/kubevirt-ssp/files/common-templates-v0.4.1.yaml
  roles/kubevirt-ssp/tasks/deprovision.yml
  roles/kubevirt-ssp/tasks/main.yml
  roles/kubevirt-ssp/tasks/provision.yml
Labels: release-note, size/XXL

#573 Replace CDI deploy tasks using its operator (#569)
  roles/cdi/README.md
  roles/cdi/defaults/main.yml
  roles/cdi/tasks/deprovision.yml
  roles/cdi/tasks/provision.yml
  roles/cdi/templates/cdi-operator-cr.yaml.j2
  roles/cdi/templates/cdi-operator.yaml.j2
  roles/cdi/templates/cdi-resourcequota.yml
Labels: release-note, size/L

#574 Add kubevirt-cpu-node-labeller deployment to kubevirt ansible
  playbooks/kubevirt-cpu-node-labeller.yml
  playbooks/kubevirt.yml
  roles/kubevirt-cpu-node-labeller/README.md
  roles/kubevirt-cpu-node-labeller/defaults/main.yml
  roles/kubevirt-cpu-node-labeller/tasks/deprovision.yml
  roles/kubevirt-cpu-node-labeller/tasks/main.yaml
  roles/kubevirt-cpu-node-labeller/tasks/provision.yml
  roles/kubevirt-cpu-node-labeller/templates/kubevirt-cpu-node-labeller-0.0.1.yaml
Labels: release-note-none

#582 Add sleep container in cpu-node-labeller to prevent restarting
  roles/kubevirt-cpu-node-labeller/tasks/deprovision.yml
  roles/kubevirt-cpu-node-labeller/tasks/provision.yml
  roles/kubevirt-cpu-node-labeller/templates/kubevirt-cpu-node-labeller-0.0.1.yaml
Labels: release-note-none, size/M

#581 Comment out view test
  tests/rbac_test.go
Labels: release-note-none, size/XS

#579 Expose CDI Upload Proxy service
  roles/cdi/tasks/deprovision.yml
  roles/cdi/tasks/provision.yml
  roles/cdi/templates/cdi-uploadproxy-route.yaml.j2
Labels: release-note, size/M

#584 3 backports
  roles/cdi/tasks/deprovision.yml
  roles/cdi/tasks/provision.yml
  roles/cdi/templates/cdi-uploadproxy-route.yaml.j2
  roles/kubevirt-cpu-node-labeller/tasks/deprovision.yml
  roles/kubevirt-cpu-node-labeller/tasks/provision.yml
  roles/kubevirt-cpu-node-labeller/templates/kubevirt-cpu-node-labeller-0.0.1.yaml
  tests/rbac_test.go
Labels: release-note-none, size/M

#585 changed oc create to oc apply in kubevirt-cpu-node-labeller
  roles/kubevirt-cpu-node-labeller/tasks/provision.yml
Labels: release-note-none, size/XS

#587 changed oc create to oc apply in kubevirt-cpu-node-labeller (#585)
  roles/kubevirt-cpu-node-labeller/tasks/provision.yml
Labels: release-note-none, size/XS

#588 change cdi-uploadproxy route name
  roles/cdi/templates/cdi-uploadproxy-route.yaml.j2
Labels: release-note-none, size/XS

#547 Added attributes and test_ids to the high_performance_vm tests
  tests/high_performance_vm_test.go
Labels: release-note-none, size/S

#577 move sr-iov config distribution to sr-iov dp manifest
  roles/network-multus/templates/cni-plugins.yml
  roles/network-multus/templates/sriovdp.yml
Labels: release-note, size/L

#551 Adds test attributes to secrets_and_cfgmap_test
  tests/secrets_and_cfgmap_test.go
Labels: release-note-none, size/XS

#420 [Tests] Add test for Multus and OVS CNI
  tests/framework/util.go
  tests/manifests/ovs-vlan-net.yml
  tests/manifests/privileged-pod.yml
  tests/network_connectivity_test.go
Labels: size/L
