Repository kubevirt/kubevirt-ansible, pull requests merged in 2019-05, with the labels that each got.

#604 Add networkpolicy test:Set connectivity to only allow from http
  tests/manifests/networkpolicy-allow-http.yml
  tests/manifests/networkpolicy-deny-all.yml
  tests/networkpolicy_test.go
Labels: release-note-none, size/L

#618 Add test for migration masquerade vm
  tests/network_migration_test.go
Labels: release-note-none, size/L

#620 quick-workaround: syntax error
  tests/network_migration_test.go
  tests/networkpolicy_test.go
Labels: release-note-none, size/M

#537 Auto tests for PR: kubevirt/kubevirt#1839
  hack/run-tests.sh
  playbooks/provider/lago/LagoInitFile.yml.j2
  roles/kubevirt_web_ui/tasks/provision.web-ui.yml
  tests/framework/types.go
  tests/framework/util.go
  tests/framework/vnc_console.go
  tests/manifests/sockets_cores_threads/vm-template-fedora-no-sockets-cores-and-threads.yaml
  tests/manifests/sockets_cores_threads/vm-template-fedora-only-cores-and-threads.yaml
  tests/manifests/sockets_cores_threads/vm-template-fedora-only-cores.yaml
  tests/manifests/sockets_cores_threads/vm-template-fedora-only-sockets-and-cores.yaml
  tests/manifests/sockets_cores_threads/vm-template-fedora-only-sockets-and-threads.yaml
  tests/manifests/sockets_cores_threads/vm-template-fedora-only-sockets.yaml
  tests/manifests/sockets_cores_threads/vm-template-fedora-only-threads.yaml
  tests/manifests/sockets_cores_threads/vm-template-fedora-sockets-cores-and-threads.yaml
  tests/manifests/sockets_cores_threads/vmi-case1.1.yml
  tests/manifests/sockets_cores_threads/vmi-case1.2.1.yml
  tests/manifests/sockets_cores_threads/vmi-case1.2.2.yml
  tests/manifests/sockets_cores_threads/vmi-case1.2.3.yml
  tests/secrets_and_cfgmap_test.go
  tests/serviceaccount_test.go
  tests/sockets_cores_threads_test.go
  tests/vm_with_sidecar_hook_test.go
  vars/all.yml
Labels: release-note-none, size/XXL
