Repository kubevirt/kubevirt-ansible, pull requests merged in 2019-02, with the labels that each got.

#519 Document SR-IOV configuration
  playbooks/README.md
Labels: release-note-none, size/M

#592 Deprovision sriov resources
  roles/network-multus/tasks/deprovision.yml
Labels: release-note-none, size/M

#596 Bump kubevirt-web-ui version
  vars/all.yml
Labels: release-note-none, size/XS

#597 Aligning registry variable in kubevirt-cpu-node-labeller to global standard
  roles/kubevirt-cpu-node-labeller/defaults/main.yml
Labels: release-note-action-required, size/XS

#598 WebUI: fix incorrect set_fact in deprovision
  roles/kubevirt_web_ui/tasks/deprovision.web-ui.yml
  roles/kubevirt_web_ui/tasks/main.yml
  roles/kubevirt_web_ui/tasks/provision.web-ui.yml
Labels: release-note, size/S

#548 adjust to ovs-cni 0.4 deployment, including marker
  roles/network-multus/defaults/main.yml
  roles/network-multus/tasks/deprovision.yml
  roles/network-multus/tasks/provision.yml
  roles/network-multus/templates/kubernetes-ovs-cni.yml
  roles/network-multus/templates/openshift-ovs-cni.yml
  roles/network-multus/templates/ovs-cni.yml
  roles/network-multus/templates/ovs-vsctl.yml
Labels: release-note, size/L

#593 VLAN to no VLAN connectivity and veth leftovers tests
  tests/framework/util.go
  tests/manifests/privileged-pod.yml
  tests/network_connectivity_test.go
Labels: release-note-none, size/M

#600 use ansible 2.7.7
  automation/check-patch.packages
Labels: release-note-none, size/XS

#602 make pip available
  automation/check-patch.packages
Labels: release-note-none, size/XS

#601 Tests add multus bond
  tests/manifests/ovs-nets.yml
  tests/network_connectivity_test.go
Labels: release-note-none, size/L
